vich_uploader:
    db_driver: orm

    mappings:
        featured_images:
            uri_prefix: '%featured_images_path%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%featured_images_path%'
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
